class MazeGenerator:
    def __init__(self, config):
        ...

    def generate(self) -> None:
        ...

    def get_grid(self) -> list[list[int]]:
        ...

    def get_solution(self) -> list[str]:
        ...